sonar.projectKey=my-nextjs-app
sonar.sources=.
sonar.exclusions=**/node_modules/**,**/.next/**,**/*.test.tsx,**/*.test.ts,**/coverage/**
sonar.host.url=http://localhost:9000
sonar.token=sqp_97289e41738da8445cc9ea66d2b9467c14202ad3